database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/userhue

camel:
  awsAccessKey:
  awsSecretKey:

throttle:
  contexts:
    - username: .*
      servletPath: .*
      ipAddress: .*
      allowedThroughput: 1

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8090
# this requires the npn-boot library on the JVM's boot classpath
#    - type: spdy
#      port: 8445
#      keyStore: example.keystore
#      keyStorePassword: example
#      validateCerts: false
  adminConnectors:
    - type: http
      port: 8091

logging:
  level: INFO
  loggers:
    com.littlesquare.crackerjack.services: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console
