database:
  driverClass: org.h2.Driver
  url: jdbc:h2:target/example

camel:
  awsAccessKey:
  awsSecretKey:

throttle:
  contexts:
    - username: .*
      method: .*
      servletPath: .*
      ipAddress: .*
      allowedThroughput: 10

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8070
# this requires the npn-boot library on the JVM's boot classpath
#    - type: spdy
#      port: 8445
#      keyStore: example.keystore
#      keyStorePassword: example
#      validateCerts: false
  adminConnectors:
    - type: http
      port: 8071

logging:
  level: INFO
  loggers:
    com.littlesquare.crackerjack.services: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console
